### ISSUE TITLE
hbsfy returns BOM character at the beginning of templated strings

### ISSUE THREAD

**Issue by ashwnacharya** [epeli/node-hbsfy#18]
var template_hbsfy = require('template.hbs');

// tmpl_string is the exact same string contained in template.hbs, read using $.ajax()
var template =  Handlebars.compile(tmpl_string);

// obj is some object
var string1 = template_hbsfy(obj);
var string2 = template(obj);

string1 and string2 are different.

string1 contains a BOM character appended to the beginning ot the string. This is interpreted as an empty text element.

**Comment by kirbysayshi** [comment]
This is now fixed as of v2.4.1! The BOM is always stripped from input.
