### ISSUE TITLE
Option to include minified version of the runtime

### ISSUE THREAD

**Issue by MathieuLoutre** [epeli/node-hbsfy#22]
Using grunt to build with `browserify`, I'm using both `hbsfy` and `uglifyify` as transforms on my code. It appears that the runtime included by `hbsfy` is not minified.

Could there be an option to have runtime.js point to `handlebars/dist/handlebars.runtime.min` instead of `handlebars/runtime`?

I could work on a PR if this sounds interesting.

**Comment by Raphaww** [comment]
@MathieuLoutre probably a little late but I was having the same problem and I found that uglifyify only applies to your application code, if you want to use in all modules you need to use global transforms (-g)

browserify -g uglifyify ./index.js > bundle.js

**Comment by MathieuLoutre** [comment]
@Raphaww thanks! That's a good find. I had let it go to be honest, but I might just put the flag and see what if it works.
