### ISSUE TITLE
How to use with custom (Ember) compiler with the browserify api?

### ISSUE THREAD

**Issue by tuckerconnelly** [epeli/node-hbsfy#33]
Hey man, trying to run hbsfy through the browserify api in a gulp task with the Ember template compiler.

This is what my task looks like:

``` js
gulp.task('browserify', function() {
    var source = require('vinyl-source-stream');
    var browserify = require('browserify');

    var bundler = browserify({
        entries: ['/js/main.js'],
        debug: true
    });

    return bundler
        .bundle()
        .pipe(source('bundle.js'))
        .pipe(gulp.dest('/build/'));
});
```

I have my browserify transforms set up in my package.json:

``` js
  "browserify": {
    "transform": [
      "browserify-shim",
      "hbsfy"
    ]
  }
```

But this doesn't compile the templates with the ember-template-compiler. How do I add that in there? Could you maybe add an example to the readme?

**Comment by GeoffreyBooth** [comment]
FYI, in current (as of June 2015) versions of Ember, you want something like this:

```json
  "browserify": {
    "transform": [
      [
        "hbsfy",
        {
          "extensions": [
            "hbs"
          ],
          "precompiler": "/path/to/your/ember-template-compiler.js",
          "compiler": "Ember.HTMLBars"
        }
      ],
```

And adjust `path/to/your` as appropriate for where you’re pulling in Ember from.
