### ISSUE TITLE
Show original markup in source map

### ISSUE THREAD

**Issue by aldendaniels** [epeli/node-hbsfy#35]
Currently, the compiled markup is shown in the browserify source map. Ideally, the original handlebars markup would be shown.

Note that other browserify transforms such as [stringify](https://github.com/JohnPostlethwait/stringify) show the original markup, so this should be doable.

Cheers - and thanks for this very useful transform.

**Comment by kirbysayshi** [comment]
@aldendaniels I took a look at this yesterday. While it's not hard in theory, I couldn't get the source maps to work properly. So this is likely not going to happen, sadly. Source maps are just really hard to debug and troubleshoot.

**Comment by aldendaniels** [comment]
@kirbysayshi - This is no problem and makes sense. Thanks for looking into it. Please feel free to close this issue if you're unlikely to get to this.

**Comment by kirbysayshi** [comment]
Closing. If anyone in the future finds this and decides to take a shot, feel free to reopen or ping for more details!
