### ISSUE TITLE
Upgrade version of handlebars

### ISSUE THREAD

**Issue by michaelBenin** [epeli/node-hbsfy#41]
https://www.npmjs.com/package/handlebars - 3.0.0

Using hbsfy with hbs. 

Related: https://github.com/donpark/hbs/issues/85

**Comment by alexkaraman85** [comment]
+1

**Comment by AdamPflug** [comment]
+1

**Comment by leiming** [comment]
+1

**Comment by epeli** [comment]
Is Handlebars 3.0 somehow broken with hbsfy? hbsfy itself does not depend on the handlebars module.

**Comment by leiming** [comment]
My current problem is using hbsfy and https://github.com/Nikku/karma-browserify always throw `bundle error`while require hbs. Here is my  karma.conf.js

```
'use strict';

module.exports = function (karma) {
  karma.set({

    frameworks: ['jasmine', 'browserify'],

    files: [
      'src/**/*.js',
      'test/**/*Spec.js'
    ],

    // possible values: 'dots', 'progress', 'junit', 'growl', 'coverage'
    reporters: ['progress'],

    preprocessors: {
      'src/**/*.js'     : ['browserify'],
      'test/**/*Spec.js': ['browserify']
    },

    browsers: ['Chrome'],

    logLevel: 'LOG_DEBUG',

    //singleRun: true,
    autoWatch: true,

    // browserify configuration
    browserify: {
      debug    : true,
      transform: ['brfs', 'browserify-shim', 'hbsfy']
    }
  });
};
```

# index.js
```
var handlebars = require('handlebars')
var template = require("./test.hbs")
var context = {title: "My New Post", body: "This is my first post!"};
template(context)
```

I would give more details if you were interesting

**Comment by leiming** [comment]
Is it possible that a lack of configure `preprocessors ` in `karma.conf.js` such as https://github.com/petrbela/karma-handlebars-preprocessor ?

**Comment by leiming** [comment]
My problem has been soloved on https://github.com/nikku/karma-browserify/issues/128#issuecomment-104418457 and https://github.com/leiming/karma-browserify-handlebars . I am tracing this issue while using Handlebars 3.0 version.

Thank you very much!

**Comment by Rrrapture** [comment]
+1

**Comment by kirbysayshi** [comment]
hbsfy does not specify handlebars as a true dependency, meaning an app (aka a developer) is meant to specify the version of handlebars specifically in their package.json. hbsfy only specifies a version of handlebars for testing purposes. npm happens to install this devDependency, meaning it's present in the dependency tree, but that side effect should not be depended upon: the app should have it's own explicit version of handlebars in its package.json as a true dependency (not a dev dependency).

As of v2.4.0, hbsfy has been tested to work with handlebars 2, 3, and 4. Installing any of those into your app should work just fine as long as you explicitly define it as a dependency.

I'm going to close this, but feel free to ask questions if there are still problems.

**Comment by kirbysayshi** [comment]
And by questions, I mean: there is a good chance I'm missing something, or that someone is experiencing something I haven't accounted for. If that's the case, I'm sorry, and please report another issue!
