### ISSUE TITLE
How to not include runtime with hbsfy

### ISSUE THREAD

**Issue by daprahamian** [epeli/node-hbsfy#42]
I am trying to write multiple small projects using hbsfy. The problem is that each of these projects includes an instance of the handlebars runtime. If someone tries to consume more than one of these projects, they get multiple copies of the runtime. Is there a way to not include the runtime when using hbsfy? Thanks!

**Comment by epeli** [comment]
Define what you mean with "project"? Node module, node app, web app?

**Comment by daprahamian** [comment]
These are meant to be web libraries. Usage involves someone adding multiple tags to the page, and either referencing the libraries directly off of the window or through a shim.

**Comment by daprahamian** [comment]
Sorry for closing this issue earlier, this is still relevant to my workflow. Is there a way to implement what I am trying to do?

**Comment by elgubenis** [comment]
i would also like to know that, i prefer defining some global helpers and then use them within browserify modules, but using the comfort of hbsfy using require to import hbs files :/

**Comment by elgubenis** [comment]
could be answered by #48 thats what i use, i forked and published hsbfy-global where i expose Handlebars to the global scope by doing window.Handlebars = require('hbsfy-global/runtime'); and then the helpers/partials are available in other bundles aswell.

**Comment by daprahamian** [comment]
I was able to finally figure this out. I first changed the hbsfy compiler to be handlebars like so:

```js
var options = {
  compiler: 'require("handlebars")'
};
```

I then used  [browserify-shim](https://github.com/thlorenz/browserify-shim) to make `handlebars` point to the global handlebars.
