### ISSUE TITLE
peerDep

### ISSUE THREAD

**Issue by chpio** [epeli/node-hbsfy#44]
Hi,

why is there no peerDep to *handlebars*.
e.g. just like before 2.0.0 but with * version:
```json
"peerDependencies": {
  "handlebars": "*"
}
```

**Comment by kirbysayshi** [comment]
I just added a commit that explains why. As a consumer of hbsfy, it's expected that you install your own version of handlebars to decouple that runtime dependency from this build dependency.

Here is the message:

I have refrained from specifying handlebars as a peerDependency for a
few reasons:

1) in npm@2, peerDependencies cause side effects on the dependency tree,
meaning dependency hell is a problem: it forces all packages, even with
their devDependencies, to use the same version of packages. This is not
realistic.

2) in npm@3, peerDependencies simply print a warning when unfulfilled.
This is superb, but I'm betting that many users have not yet
upgraded to npm@3 yet.

**Comment by kirbysayshi** [comment]
In other words, if the entire world were using npm@3, I'd have no problem specifying a peerDependency, and would love to do so! It would help make tests more stable. But until then there is too great a risk of breaking builds that aren't actually broken.
