### ISSUE TITLE
use global Handlebars

### ISSUE THREAD

**Issue by elgubenis** [epeli/node-hbsfy#48]
hi, is there an easy way to configure grunt-browserify to use hbsfy transform but with the global Handlebars variable available?

**Comment by kirbysayshi** [comment]
I can't speak for grunt-browserify, but if you were using just browserify:

```
$ browserify -t [ hbsfy -c 'Handlebars' ] index.js > bundle.js
```

The `-c` is the "compiler" to use, which means the runtime instance of Handlebars. It defaults to the string `"require('hbsfy/runtime')"`, so if you use `"Handlebars"` instead that will compile inside the template to `var compiler = Handlebars` which will reference the global.

Please reopen if this doesn't help or you still have troubles!

**Comment by elgubenis** [comment]
thx
