### ISSUE TITLE
Hbsfy fails to use aliases while using --traverse

### ISSUE THREAD

**Issue by kentmw** [epeli/node-hbsfy#56]
I am using the transform aliasify (https://github.com/benbria/aliasify) to stop the crazy `../../../../../../` problem of referencing a file far away.

This is my setup:
```
  var browserify = require('browserify');
  var b = browserify();
  b.add('./app/init');
  b.transform('aliasify');
  b.transform('hbsfy', { traverse: true });
```
and this is my package.json aliasify configuration:
```
{
  "aliasify": {
    "aliases": {
      "app": "./app"
    }
  }
}
```
and I'm referencing this alias in my templates:
```
  {{> app/myPartial.hbs }}
```
And when I run the bundle it still complaining it can't find that module.

I realize that aliasify is separate from hbsfy and there's no reason why they would have to work together. But, I was wondering if people have found a way around the `../../../../../../` problem using --traverse flag

**Comment by kentmw** [comment]
I wonder if this is solved by having aliasify also --traverse field, that goes into handlebars files. The other way it could work is if hbsfy brought in the aliasify's configuration and used that when inspecting which partial to reference.

**Comment by kirbysayshi** [comment]
If you change the order of your transforms, putting aliasify before hbsfy, does that work?

```
  var browserify = require('browserify');
  var b = browserify();
  b.add('./app/init');
  b.transform('hbsfy', { traverse: true });
  b.transform('aliasify');
```

**Comment by kentmw** [comment]
I had the same idea, no change. It seems like that would have fixed it.
I have 2 hypothesis right now that I'm testing:

1. The transforms are running in parallel so you can't guarantee hbsfy is finished before aliasify starts. Some experiments seem to suggest this is true. I threw in some console.logs in both transform libraries, and both hbsfy and aliasify were dumping things to the terminal at the same time.

2. Aliasify isn't targeting handlebars files. I doubt this, but still could be a reason.

**Comment by kentmw** [comment]
Does the `hbsfy` function have any asynchronous aspect to it? Will the `hbsfy` function ever complete before it has completed updating the files? It doesn't [look](https://github.com/substack/node-browserify/blob/master/index.js#L83-L86) like they handle promise resolution, and they expect everything to be completed with the transform returns.

**Comment by kentmw** [comment]
Just kidding, user @jmm pointed out that aliasify is targeting only javascript files (which happened to be my second hypothesis). I'll make a pull request in aliasify to allow hbs files.

**Comment by kentmw** [comment]
Just for people looking into this, there is an `appliesTo` option for `aliasify` that you can specify the files you want aliasify to work on.

This was what I had to change to get this to work:
```
  "aliasify": {
    "aliases": {
      "app": "./app",
    },
    "appliesTo": {"includeExtensions": [".js", ".hbs"]}
  }
```

**Comment by kirbysayshi** [comment]
Browserify transforms are streams, so they are asynchronous by nature. But the order of transforms does matter, as for a particular file the transforms will be applied in order.

Glad you figured it out!

**Comment by rafegoldberg** [comment]
@kentmw's suggestion (re: the `aliasify.appliesTo.includeExtensions` option) works like a charm – for those interested, I'd add that you have to run the `aliasify` transform **_after_** `hbsfy`. Otherwise aliasify first else it tries to parse your Handlebars files as Javascript syntax which will obviously throw a shit-load of errors all over the place!
