### ISSUE TITLE
Using helpers through command-line

### ISSUE THREAD

**Issue by yamsellem** [epeli/node-hbsfy#57]
The doc don't clearly stated how to register helpers with the command line (_and if it's even possible_).

So is there a way to add the following helper to the `-t` options?
`browserify -t [ hbsfy -e html,htm ] main.js > bundle.js`

``` javascript
var Handlebars = require("hbsfy/runtime");
Handlebars.registerHelper("upcase", function(s) {
  return s.toUpperCase();
});
```

**Comment by yamsellem** [comment]
I find the ugliest fix ever.

Running:
`browserify -t [hbsfy -e hbs -c require("handlebars-helpers")] main.js > bundle.js`

And defining an external module known through `npm link` in its folder and `npm link handlebars-helpers` in `main.js` folder:

index .js
```javascript
var hbs = require("hbsfy/runtime");
hbs.registerHelper('equal', function(lvalue, rvalue, options) {
    if (arguments.length < 3)
        throw new Error("Handlebars Helper equal needs 2 parameters")
    if (lvalue != rvalue)
        return options.inverse(this)
    else
        return options.fn(this)
});
module.exports = hbs;
```

package.json
```javascript
{
    "name": "handlebars-helpers",
    "main": "index.js",
    "dependencies": {
        "handlebars": "x"
    }
}
```

I really don't understand why the compile option is waiting for a `"require('module')"` as a string instead of the npm module name.

This seems like 'a fixing the hell option' more than a proper solution, so not closing the issue for the time being.

**Comment by kirbysayshi** [comment]
Registering a helper on the command line raises a lot of questions about how that would work. Probably too many to solve via a CLI, especially when I believe everything you want to do can be accomplished using the existing API. For example:

```
// helpers.js
module.exports = function (hbs) {
  hbs.Handlebars.registerHelper("upcase", function(s) {
    return s.toUpperCase();
  });
  return hbs;
}

// index.js (your app entry file)
var Handlebars = require("hbsfy/runtime");
require('./helpers')(Handlebars);
```

**Comment by kirbysayshi** [comment]
I'm going to close this, but feel free to reopen it if this doesn't help.
