### ISSUE TITLE
Babel plugin

### ISSUE THREAD

**Issue by DylanPiercey** [epeli/node-hbsfy#58]
This is obviously out of scope for this particular package but currently their just isn't a good babel handlebars plugin. I've tried to mess around and create one but truthfully babel plugins confuse me.

For me personally this would resolve #51.

If you'd be interested in making one that would be amazing.
Feel free to close this issue if this isn't something you'd consider doing.

**Comment by kirbysayshi** [comment]
Hey, sorry for the delay @DylanPiercey. A babel plugin isn't something I'd like to work on (or bring into this package), as I'd like to keep this package browserify-focused.
