### ISSUE TITLE
Error: You specified knownHelpersOnly, but used the unknown helper

### ISSUE THREAD

**Issue by gitlovenotwar** [epeli/node-hbsfy#59]
Partial and custom helpers causes errors. Ex.

{{> myPartialTemplate.hbs}}

{{#myCustomHelper param}}

{{/myCustomHelper}}

This causes errors saying. You specified knownHelpersOnly, but used the unknown helper "myCustomHelper". I am using this in webpack.

**Comment by kirbysayshi** [comment]
Are you implying that `{{> myPartialTemplate.hbs}}` contains a helper called `myCustomHelper`? Otherwise I'm not sure what's happening here.

**Comment by kirbysayshi** [comment]
Going to close this, feel free to reopen with more details!
