### ISSUE TITLE
honor Browserify "paths" when resolving partials?

### ISSUE THREAD

**Issue by rafegoldberg** [epeli/node-hbsfy#62]
the ability to resolve partials by relative path (via the `--traverse` flag) is great, but all the dots and slashes can get cumbersome quickly. I was wondering if there was a to get HBSfy to "honor" my Browserify `paths` setting somehow?

so for example, say I had the following files:

```
app/
├ templates/
│ └─item.hbs
└ views
  └ page/
    └─layout.hbs
```

if I wanted to use the `item.hbs` partial in my **`layout.hbs`** template I'd have to write out the entire relative path to the file. instead, it'd be awesome if `hbsfy` could somehow resolve partial paths against those I've set in my Browserify options! so that if I'd got it configured something like:

```js
// in a gulpfile.js task or package.json entry or wherever
Browserify({
  entry:["src/index.js"],
  paths:["app/templates"] // HBSfy would resolve paths against this option
  })
```

now, in my faraway template I could simply write:

```hbs
<!-- let's say in app/Views/Page/layout.hbs -->
{{#each items}}
  {{> templates/item.hbs }}
{{/each}}
```

instead of the fully qualified `{{> ../../templates/item.hbs }}` relative path.

---

hope that made a shred of sense, but honestly not sure — let me know if I can clarify!

**Comment by kirbysayshi** [comment]
This should be possible if you modify NODE_PATH as well as browserify’s
path. But I don’t recommend it: once you start doing custom path resolution
you need to do it everywhere!

**Comment by rafegoldberg** [comment]
@kirbysayshi ahha, interesting take on why "relative path hell" is maybe not so hellish! will take said advice in to consideration. and thanks for pointing me towards `NODE_PATH` just in case.

**Comment by rafegoldberg** [comment]
for posterity: I managed to achieve a similar effect using [`aliasify`](https://github.com/benbria/aliasify) along with the configuration suggested in #56.
